theme = "ayu_dark"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor]
line-number = "relative"
auto-info = true
auto-completion = true
completion-trigger-len = 2
true-color = true
shell = ["nu", "-c"]
cursorcolumn = true
cursorline = true
bufferline = "always"
mouse = false
middle-click-paste = false

[editor.file-picker]
hidden = true
git-global = true
git-ignore = true
parents = true

[editor.lsp]
display-messages = true

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
"'" = "'"
'`' = '`'
'<' = '>'

[editor.search]
smart-case = true
wrap-around = true

[keys.normal]
"C-l" = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
C-y = ":sh zellij run -c -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh open"
