theme = "ayu_dark"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor]
line-number = "relative"
auto-info = true
auto-completion = true
completion-trigger-len = 2
true-color = true
shell = ["nu", "-c"]
cursorcolumn = true
cursorline = true
bufferline = "multiple"
mouse = false
middle-click-paste = false

[editor.file-picker]
hidden = true
git-global = true
git-ignore = true
parents = true

[editor.lsp]
display-messages = true

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
"'" = "'"
'`' = '`'
'<' = '>'

[editor.search]
smart-case = true
wrap-around = true
